server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # SPA: все неизвестные маршруты отдаём на index.html, чтобы работал React Router
    location / {
        try_files $uri $uri/ /index.html;
    }
}
